### PR TITLE
Improve rendering performance

### PR DESCRIPTION
**Pull request by Calinou**
**Don't merge before 3.4 is released, as this relies on occluder spheres and other 3.4-only features.**

- Replace GIProbe with BakedLightmap. This alone speeds up scene rendering by at least 2× (if not more). The scene is lit in a different way (brighter overall now), but this also helps make it more readable.
  - Lightmap object capture is disabled as it would have created a file that's too large to be committed on GitHub (which imposes a 20 MB per file limit).
  - HDR is disabled on the lightmap to reduce its file size below 20 MB. Clipping or banding isn't really visible since only indirect lighting is baked anyway.
  - Reflection probes are used instead to provide reflections and improve the appearance of dynamic objects.
  - Reduce SSAO intensity to compensate for the lighting being brighter on average.
- Add fill lights to dynamic objects with a cull mask set to only impact themselves.
- Use the cheaper Lambert diffuse mode for materials.
- Set specular mode to Disabled on materials that don't need specular lighting.
- Disable shadows for most lights (they made little visual difference). This divides draw calls by 3 on average.
- Add occluder spheres. Gains are minor due to GLES3 already having a depth prepass and the level only having a few occlusion culling opportunities, but they're present in certain situations.

The GI setting was removed as it's no longer relevant.

Disabling shadows for non-essential lights and adding occluder spheres brings down the number of draw calls from 10k-15k to 2k-6k. (Most of the gains are from disabling shadows.)

## Performance

**CPU:** Intel Core i7-6700K
**GPU:** GeForce GTX 1080 (NVIDIA 470.74)
**OS:** Fedora 34

Performance measured at start area (after starting a game and waiting a few seconds):

| Settings | Before | After |
|----------|--------|-------|
| High settings* | 60 FPS (16.7 mspf) | 118 FPS (8.5 mspf) |
| Low settings* | 135 FPS (7.4 mspf) | 200 FPS (5 mspf) |

*High settings:* 2560×1440, MSAA 4×, AO High, Glow High, GI High (if relevant)
*Low settings:* 2560×1440, MSAA Off, AO Off, Glow Off, GI Off (if relevant)

Note that in certain areas of the level, the performance gains are even greater. With AO disabled but Glow kept to high, it's uncommon to go below 144 FPS during gameplay now. This makes for a much better experience on a 144 Hz monitor :slightly_smiling_face: 

## Preview

*Some visual cutbacks were made, but they usually aren't noticeable unless you go looking for them.*

### CODE REVIEW

**Comment by aaronfranke** [comment]
Both the before and after screenshots in your latest posts are *massively* brighter than the current version (and, full disclaimer, I think this looks significantly worse). I think that the current aesthetic of the demo is good and shouldn't be massively changed.

Significantly changing the appearance of the demo also really shouldn't be tied to improving performance. If we have to make the demo look significantly worse to improve performance, is that actually an improvement?

**Comment by aaronfranke** [comment]
Here is what I see after building the latest 3.x, clearing `.import/`, and opening this PR: https://imgsli.com/NzcyNjk

I can reproduce the bright ground, but it still looks significantly worse.

**Comment by SeaFishelle** [comment]
What's the purpose behind making the _visual_ demo more performant? Isn't the whole point to show the graphical capabilities of the engine? Why actively make the demo look worse to improve its performance? That seems kind of backwards to me. Especially since it's just a demo, not a template or asset pack or anything like that.

And if the argument is so that users on lower-end hardware can see the demo... it's a _visual_ demo. They can watch videos and get the same point across.

**Comment by Calinou** [comment]
> What's the purpose behind making the _visual_ demo more performant? Isn't the whole point to show the graphical capabilities of the engine? Why actively make the demo look worse to improve its performance? That seems kind of backwards to me. Especially since it's just a demo, not a template or asset pack or anything like that.
> 
> And if the argument is so that users on lower-end hardware can see the demo... it's a _visual_ demo. They can watch videos and get the same point across.

The demo is currently not quite smooth on high-end hardware from a few years ago. A GTX 1080 is still significantly faster than the [most popular GPU on Steam as of writing, which is a GTX 1060](https://store.steampowered.com/hwsurvey).

This gives a bad image of Godot to people who try it on mid-range hardware and dismiss it as a low-performance option compared to other engines.

**Comment by Calinou** [comment]
> Why not upload it as a separate demo? something like "TPS demo - performance optimized"?

To avoid confusion, we can't have too many similar-looking demos lying around.

**Comment by Nukiloco** [comment]
Looking at the after images, the entire quality seem to be much worse than it was before. I'm also going to recommend not to merge or change this at all and keep it the same.
In my opinion this demo is supposed to show how good Godot is at visual stuff, lowering down the quality of it is going to make it look worse and might get some new comers not interested at all.

>
> This gives a bad image of Godot to people who try it on mid-range hardware, and then dismiss it as a low-performance option > compared to other engines. This is something I've seen happen time and time again on various community platforms (inside and outside active Godot users). Overall, I've seen more people complain about Godot's poor 3D performance rather than poor visuals.

The engine in this case is what needs to be optimized here. Lowering down the quality of the game will make the situation even worse than it is before and doesn't fix the overall problem that your explaining here.

In my opinion and I think that we as a community, should take step back and look at the whole graphical part of the engine to see what can be optimized and fixed before making any changes to the demo itself. When I think of optimizations, I don't think of major graphical stuff that shows the engine's potential being cut just to fix a problem.

**Comment by Nukiloco** [comment]
And even if those engine optimizations aren't enough, I think a better solution is to bring in graphical options into the demo to allow the user to toggle between high and low graphics for computers with low end or high end specs.

**Comment by Jamsers** [comment]
Why does switching from GI Probe to Baked Lightmap reduce quality so much? Shouldn't Baked Lightmap actually produce higher quality results, albeit at a bigger cost to storage? I've tried it myself with my own copy of the TP demo and it does produce flat, bad lighting

**Comment by Calinou** [comment]
> Why does switching from GI Probe to Baked Lightmap reduce quality so much? Shouldn't Baked Lightmap actually produce higher quality results, albeit at a bigger cost to storage? I've tried it myself with my own copy of the TP demo and it does produce flat, bad lighting

Baked lightmaps in 3.x only store diffuse lighting, not specular lighting. They also don't store directional information in 3.x, although GIProbes don't do that either for indirect lighting.

Baked lightmaps are also much less prone to leaks, but GIProbe leaking is barely noticeable in the TPS demo since it's an indoor scene.

**Pull request closed without merging**
