### PR TITLE
Increase the tonemap White value to make highlights less blown out

### PR DESCRIPTION
**Pull request by Calinou**
This incorporates settings from https://github.com/godotengine/godot/pull/34798 into the TPS demo.

### Before

editor_screenshot_2020-09-15T212347+0200

### After

editor_screenshot_2020-09-15T212339+0200

### CODE REVIEW

**Comment by Jummit** [comment]
ImgSli just for fun: https://imgsli.com/MjIyNDQ

**Comment by aaronfranke** [comment]
I don't know if these changes actually meet the goal in the title of making highlights less blown out. In the images you posted, it seems that highlighted areas are brighter and more blown out. For example, look at the blue pillar in the middle, and the orange illuminated wall on the right (with the trapezoid shaped pieces).

This mostly seems to increase the contrast of the demo. The colors are more vibrant, brights are brighter, darks are darker.

Before:

Screenshot from 2020-09-15 15-34-22

After:

Screenshot from 2020-09-15 15-34-43

Before:

Screenshot from 2020-09-15 15-40-03

After:

Screenshot from 2020-09-15 15-40-13

**Comment by Calinou** [comment]
@aaronfranke It will probably work better if I tweak the glow settings at the same time, let me try that.

**Comment by aaronfranke** [comment]
It seems that now the net effect is that colors look better, but it's darker: https://imgsli.com/MjIyNDg

The highlights are definitely less blown out. I asked a few people on Discord and the general consensus is that this PR is an improvement but it is darker. Maybe you can tweak it a bit more and find some way that looks good but makes it not so dark, I tried playing around with the settings and there was no obvious fix that I could see, but otherwise I think this is a good PR overall.

**Review by aaronfranke — APPROVED** [review]
I think this is good.

**Pull request merged**
