### PR TITLE
Fixed several visual errors that only appeared under Linux

### PR DESCRIPTION
**Pull request by jlogostini**
I have updated several materials to fix problems under Linux primarily transparent materials showing as opaque and a few just failing to load on Linux but working fine on Windows and I fixed the Button font in the Main Menu displaying way too thin i have linked a few screenshots to demonstrate the problem as of this pull request Linux and Windows look identical in the cases shown below

**Linux**
Main Menu Font _Linux
**Windows**
Main Menu Font _Windows
**Linux**
Gun_Blast_Linux
**Windows**
Gun_Blast_Windows

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally in 4.3.dev 0bcc0e92b (Linux), it works as expected.

Thanks!

**Comment by akien-mga** [comment]
The modified files were all made executable by mistake.

**Comment by jlogostini** [comment]
@akien-mga opps do I change that then recommit the files or just leave it?

**Comment by jlogostini** [comment]
@Calinou Thanks for accepting my first ever PR

**Comment by akien-mga** [comment]
> @akien-mga opps do I change that then recommit the files or just leave it?

No worry, I fixed it up in 32f43f4b55bc6f548d59c4f42b13b9fc38baddea.

**Comment by akien-mga** [comment]
And congrats for your first merged Godot contribution :tada:

**Comment by jlogostini** [comment]
@akien-mga thanks :+1:

**Pull request merged**
