### PR TITLE
Implement fire cooldown

### PR DESCRIPTION
**Pull request by aBARICHELLO**
Rebased version of #10

### CODE REVIEW

**Comment by aBARICHELLO** [comment]
Should be good now @aaronfranke

**Comment by aaronfranke** [comment]
I think it's a bit slow. The old PR had a value of 0.5. I played around with it and 0.4 feels pretty good.

**Comment by aBARICHELLO** [comment]
Done!

**Comment by aaronfranke** [comment]
Thanks!

**Pull request merged**
