### PR TITLE
Tweak environment tonemapping and adjustments for Godot 3.4

### PR DESCRIPTION
**Pull request by Calinou**
- Use the new [ACES Fitted tonemapping](https://github.com/godotengine/godot/pull/52477) for physically correct behavior of glowing lights.
- Decrease overall saturation and contrast for a less jarring appearance.

Additionally, I've thought about adding subtle ambient lighting to prevent some areas from being too dark, but this is likely better done in a separate PR. We could also increase some lights' ranges and tweak their attenuation, but this may impact performance negatively as lights may impact more meshes.

**Note:** Don't merge before Godot 3.4 is released to avoid breaking the scene's appearance in 3.3.x.

## Preview

| Before | After |
|-|-|
| Before | After |

### CODE REVIEW

**Comment by aaronfranke** [comment]
Lowering the contrast and whitening bright lights is a subjective change, so I'd like to get feedback on this first.

It may be better to instead lower the brightness of the blue lights, since AFAIK the deepish blue was the artistic intent.

**Comment by Calinou** [comment]
> It may be better to instead/also lower the brightness of the blue lights, since AFAIK the deepish blue was the artistic intent.

We could ask Fernando on Twitter about this :slightly_smiling_face: Does he have a GitHub account to comment on this issue?

**Comment by Lauson1ex** [comment]
I like it! Looks very cinematic. I'm also all in for changing the attenuation curve of lights.

**Comment by Calinou** [comment]
I DM'd Fernando on Twitter and he told me that he likes the new appearance, so this should be good to merge once 3.4 is released :slightly_smiling_face:

**Review by aaronfranke — APPROVED** [review]

**Pull request merged**
