### PR TITLE
Ignore files with .import extension

### PR DESCRIPTION
**Pull request by gamedevshirious**
adding *.import to .gitignore

### CODE REVIEW

**Comment by hpvb** [comment]
This is not correct. The `.import` *directory* should be ignored but `<file>.import` contain important settings for reconstructing the project. You should never `.gitignore` `.import` it will break your projects.

**Comment by gamedevshirious** [comment]
> This is not correct. The `.import` _directory_ should be ignored but `<file>.import` contain important settings for reconstructing the project. You should never `.gitignore` `*.import` it will break your projects.

Thanks for that info. I was not aware of that, I'll have that change in my .gitignore too :)

**Comment by hpvb** [comment]
No worries! I'm glad you caught it in time! :D

**Comment by Calinou** [comment]
Note that in 4.0, the `.import` *folder* has been renamed to `.godot` to avoid confusion. For 4.0 projects, you should have `.godot/` in your `.gitignore` file.

**Pull request closed without merging**
